etc/init.d/massive-passive-client etc/init.d
etc/default/massive-passive-client etc/default
etc/massive-passive/checks.d/first_check.cfg usr/share/massive-passive-client/examples/
etc/massive-passive/checks.d/second_check.cfg usr/share/massive-passive-client/examples/
massive-passive-client usr/sbin/
README.txt usr/share/doc/massive-passive-client/
LICENSE.txt usr/share/doc/massive-passive-client/

